image:
  repository: 774305591014.dkr.ecr.us-east-1.amazonaws.com/fast_api
  tag: "7b5595e"

replicaCount: 4

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  host: fastapi.local  

rollout:
  canary:
    enabled: false
  bluegreen:
    enabled: true
