image:
  repository: 774305591014.dkr.ecr.us-east-1.amazonaws.com/fast_api
  tag: "f8aa19e"

replicaCount: 4

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  host: fastapi.local  

rollout:
  canary:
    enabled: true
  bluegreen:
    enabled: false

  analysis:
    enabled: true
    interval: 30s
    successCondition: "result[0] >= 0.95"
    failureLimit: 3
    prometheusUrl: http://prometheus-light.fastapi-namespace.svc.cluster.local:9090
    query: |
      sum(rate(http_requests_total{status!~"5.."}[2m])) /
      sum(rate(http_requests_total[2m]))
  
