apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "fastapi.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    canary:
      canaryService: {{ include "fastapi.fullname" . }}-canary
      stableService: {{ include "fastapi.fullname" . }}-stable
      trafficRouting:
        alb:
          ingress: fastapi-ingress
          servicePort: 8000

      steps:
      - setWeight: 20
      - pause: { duration: 2m }
      - setWeight: 50
      - pause: { duration: 2m }
      - setWeight: 100

  selector:
    matchLabels:
      app: fastapi

  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: fastapi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
