{{- if .Values.rollout.bluegreen.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    blueGreen:
      activeService: fastapi-app-stable
      previewService: fastapi-app-canary
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
{{- end }}
